export const USUARIOAPI = {

    login: 'ruslanguns',
    id: 19806968,
    node_id: 'MDQ6VXNlcjE5ODA2OTY4',
    avatar_url: 'https://avatars2.githubusercontent.com/u/19806968?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ruslanguns',
    html_url: 'https://github.com/ruslanguns',
    followers_url: 'https://api.github.com/users/ruslanguns/followers',
    following_url: 'https://api.github.com/users/ruslanguns/following{/other_user}',
    gists_url: 'https://api.github.com/users/ruslanguns/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ruslanguns/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ruslanguns/subscriptions',
    organizations_url: 'https://api.github.com/users/ruslanguns/orgs',
    repos_url: 'https://api.github.com/users/ruslanguns/repos',
    events_url: 'https://api.github.com/users/ruslanguns/events{/privacy}',
    received_events_url: 'https://api.github.com/users/ruslanguns/received_events',
    type: 'User',
    site_admin: false,
    name: 'Ruslán González',
    company: 'Web Developer',
    blog: 'rusgunx.tk',
    location: 'Las Palmas de Gran Canaria',
    email: null,
    hireable: true,
    bio: 'Simplemente disfruto estudiar y poner en práctica interesantes ...',
    public_repos: 33,
    public_gists: 1,
    followers: 2,
    following: 21,
    created_at: '2016-06-07T21:01:05Z',
    updated_at: '2019-02-27T14:34:09Z'
};
